### ISSUE TITLE
nayakReComprehensiveStudy

### ISSUE THREAD

**Issue by koustuvsinha** [ReScience/NeurIPS-2019#10]
Complete formatting of existing Latex files to [ReScience Template](https://github.com/ReScience/template).

**Comment by koustuvsinha** [comment]
CC-ing @nancy-nayak to check if all meta-data and organization is good. For any changes, submit a PR linking this issue.

**Comment by nancy-nayak** [comment]
Hi,
This is to acknowledge the email regarding camera ready version.
We will update our draft soon.
Regards,
Nancy

**Comment by nancy-nayak** [comment]
Hi,
After adding detail to meta data, the replication line above abstract reads
```
A replication of helwegen2019latent .
```
Only the bib key is getting included and not the publication details.
The compiled PDF is available at https://github.com/nancy-nayak/NeurIPS-2019/blob/nayak/nayakReComprehensiveStudy/journal/article.pdf

How can I fix this?

CC: @v-i-s-h

**Comment by rougier** [comment]
Did you use `\cite{}` (or better, `\fullcite{}`) ?

**Comment by nancy-nayak** [comment]
Hi,
Thanks a lot for the help.
The pull request is created.
Kindly do the needful.
