### ISSUE TITLE
Format singhReMixupTraining

### ISSUE THREAD

**Issue by koustuvsinha** [ReScience/NeurIPS-2019#11]
Complete formatting of existing Latex files to [ReScience Template](https://github.com/ReScience/template).

**Comment by koustuvsinha** [comment]
CC-ing @Macromayhem to check if all meta-data and organization is good. For any changes, submit a PR linking this issue.

**Comment by paganpasta** [comment]
@koustuvsinha Pull request has been created after adding required fields to the metadata.yaml
