### ISSUE TITLE
Unused figures folder and numerous compile erros

### ISSUE THREAD

**Issue by AlexandrosFerles** [ReScience/NeurIPS-2019#27]
Hi, what is the purpose of the figures folder in our journal folder (ferlesReZeroShotKnowledge folder paper)? Seems like has been left from a different work. 

Also, we gen numerous compile errors with the make command for very basic stuff such as 'Package biblatex Error: Command '\cite' undefined.' and 'Package keyval Error: useauthor undefined.'

How can these be fixed?

**Comment by koustuvsinha** [comment]
Yes the figures folder is leftover from another folder (apologies as I was using one folder as "template"). I'll remove that. 

As for compilation issues, can you post the error log here?

**Comment by AlexandrosFerles** [comment]
[article.log](https://github.com/ReScience/NeurIPS-2019/files/4382044/article.log)

**Comment by AlexandrosFerles** [comment]
Hi, I posted the article.log file as it is at the moment

**Comment by koustuvsinha** [comment]
~I think you are missing a lot of imports. Make sure the imports are defined properly in article.tex~

Double checked, the imports are fine.

**Comment by koustuvsinha** [comment]
FYI I did not face any compilation issues by `make` in the `ferlesReZeroShotKnowledge/journal` folder.

**Comment by AlexandrosFerles** [comment]
Hi, thanks for the swift response. 

What kind of imports do you refer to? All the needed packages from our side are available in the packages.tex file of the opener view folder which you have added an input command to, so I guess that should be enough.

Regarding the make command, what is the Tex stack which you use? 

FYI I also needed to add the file bibtex.sty, logreq.sty and logreq.def which were missing from the folder and make command exited with error because it could not find them. Is this the proper way?

**Comment by koustuvsinha** [comment]
@AlexandrosFerles , I just [compiled your paper here](https://github.com/ReScience/NeurIPS-2019/blob/master/ferlesReZeroShotKnowledge/journal/article.pdf). To compile, navigate to `ferlesReZeroShotKnowledge/journal` and run `make`. This uses latexmk (pdflatex) to generate the file. You can view the [Makefile here](https://github.com/ReScience/NeurIPS-2019/blob/master/ferlesReZeroShotKnowledge/journal/Makefile). I use tex-live stack in mac.

**Comment by koustuvsinha** [comment]
@AlexandrosFerles, did this resolve the issue?

**Comment by koustuvsinha** [comment]
Closing as the compilation works on our end.

**Comment by AlexandrosFerles** [comment]
Hi @koustuvsinha I have been following these steps from the beginning but still get the errors mentioned previously. Nevertheless, we checked the compiled paper from your end which is as expected, so you can use this for the journal publication.
