### ISSUE TITLE
Format ferlesReZeroShotKnowledge

### ISSUE THREAD

**Issue by koustuvsinha** [ReScience/NeurIPS-2019#3]
Complete formatting of existing Latex files to [ReScience Template](https://github.com/ReScience/template).

**Comment by koustuvsinha** [comment]
CC-ing @AlexandrosFerles,  @AlexLacson​ and @valavanisleonidas to check if all meta-data and organization is good. For any changes, submit a PR linking this issue.

**Comment by valavanisleonidas** [comment]
Hello, I filled the metadata.yaml and then when compiling I have the following error 

make[1]: *** No rule to make target `article.bbl'.  Stop.
Some help would be appreciated. 
Thanks

**Comment by rougier** [comment]
You can try to make again or a manual `biber article`
