### ISSUE TITLE
Format kvimanReTensorMonte

### ISSUE THREAD

**Issue by koustuvsinha** [ReScience/NeurIPS-2019#6]
Complete formatting of existing Latex files to [ReScience Template](https://github.com/ReScience/template).

**Comment by okviman** [comment]
Hi Koustuv,

We're acknowledging your message per e-mail. Thank you for finding us there., my Git notifications were switched off for some reason.

**Comment by okviman** [comment]
The fields which should be filled in with information from the editor, is it possible to get ahold of these right away?

**Comment by aradove** [comment]
Hi!

We think we have corrected what needs to be done. Can you (@koustuvsinha ) check that everything is correct?
