### ISSUE TITLE
Format liljeforsReUnsupervisedScalable

### ISSUE THREAD

**Issue by koustuvsinha** [ReScience/NeurIPS-2019#7]
Complete formatting of existing Latex files to [ReScience Template](https://github.com/ReScience/template).

**Comment by koustuvsinha** [comment]
CC-ing @lilfelix, @MoeinSorkhei, and @sofiabroome to check if all meta-data and organization is good. For any changes, submit a PR linking this issue.

**Comment by MoeinSorkhei** [comment]
Hi,

Thanks for your comments.
Firstly, we are trying to update the `metadata.yaml` file and run the command `make` again. It seems that it does not recognize the references bibliography file and the references in the created pdf file are not clickable. In the `metadata.yaml` we have specified the `bibliography.bib` file in the field `bibliography`. This is the error that we get (after a lot of warnings for citations):

![Screenshot 2020-03-10 at 13 03 44](https://user-images.githubusercontent.com/17333029/76310817-d89ad700-62cf-11ea-8b1b-c8870ce34600.png)


It seems that it is looking for `refs.bib` which is our original bib file, but that file is in the `openreview` directory.

Secondly, it seems that `\textbf` commands are not working in the created pdf file, although they are present in the `content.tex` file (especially in the tables where it is very important).

Could you help us with these matters?
Thanks for your time.

**Comment by koustuvsinha** [comment]
can you run `make clean` first before running `make`? also, it would be great if you can post the log from make here in a pastebin url.

**Comment by MoeinSorkhei** [comment]
Thanks for your response.

When I run `make clean` I get:
`Latexmk: This is Latexmk, John Collins, 17 March 2019, version: 4.63b.
Latexmk: Disallowing switch of the output file as incompatible with file requests.`
I think this has to do with the `latexmk -CA` command in `Makefile`.

Here is the output of `make` when `bibliography.bib` (the bib file present in the `journal` folder is specified for references):
https://pastebin.com/6NCnCU14
