### ISSUE TITLE
Format liuReWhenTrust

### ISSUE THREAD

**Issue by koustuvsinha** [ReScience/NeurIPS-2019#8]
Complete formatting of existing Latex files to [ReScience Template](https://github.com/ReScience/template).

**Comment by koustuvsinha** [comment]
CC-ing @GTYutingLiu, @jxu43, and @ME7ON. The compilation errors are due to two reasons:

1. Major: Please create a bibliography.bib file and convert your references into the proper bibtex fomat.
2. Minor: changing the `_`  in metadata.yaml to `\_`, i.e the mail should look like this: `yuting\_liu@brown.edu`

**Comment by GTYutingLiu** [comment]
Hi, sorry for the late response! I have fixed the compilation errors and opened a new pull request. Also, I have updated the meta-data.yaml file. Please check if there is anything else that needs to be fixed! Just let me know :) 
(BTW, all the things can be compiled by running "make" now and there are no seemingly bugs)
